### ISSUE TITLE
Nested Splitcontainer

### ISSUE THREAD

**Issue by gle4711** [jsakamoto/Toolbelt.Blazor.SplitContainer#2]
Hello, 
I have tried to build a nested splitter.  I notice that I can no longer move the second vertical splitter bar. What have I done wrong?

https://user-images.githubusercontent.com/62564122/215343099-35e1c44f-4823-4eb7-a561-3a71eec2c913.mp4

[App.zip](https://github.com/jsakamoto/Toolbelt.Blazor.SplitContainer/files/10530352/App.zip)

**Comment by jsakamoto** [comment]
@gle4711  Thank you for your reporting!

That is a bug by me. I fixed it and released the new version.

https://www.nuget.org/packages/Toolbelt.Blazor.SplitContainer/1.1.1#release-body-tab

The attached actual sample code and video allowed me to fix it quickly. Those attachments were really helpful for me to reproduce and fix the problem.

Again, thank you for your contributions!
