### ISSUE TITLE
Unable to set css class for pane

### ISSUE THREAD

**Issue by franky1017** [jsakamoto/Toolbelt.Blazor.SplitContainer#7]
I am trying to set some css classes for each individual panes but was unable to do so. For example, I might add some coloring or hiding the left pane on mobile.

How do I add these classes?

Thanks!

**Comment by jsakamoto** [comment]
Hi @franky1017,

You must be able to do that, like below, without any matters.

```html
<SplitContainer>
    <FirstPane>
        <div class="you can add any CSS classes here">
            1st Pane
        </div>
    </FirstPane>
    <SecondPane>
        <div class="you can add any CSS classes here">
            2nd Pane
        </div>
    </SecondPane>
</SplitContainer>
```

How did you try to do that? What does "unable to do" mean? Did the build errors happen? Or, there are no errors but the CSS classes you applied didn't show up? It would be helpful for me if you attached your code here.

**Comment by franky1017** [comment]
I did try your method, however, it will always generate the first pane. I
would like to apply class direct to first pane when I need to hide this,
like this:

<SplitContainer>
    <FirstPane CssClass="*mobile-hide*">
        <div class="you can add any CSS classes here">
            1st Pane
        </div>
    </FirstPane>
    <SecondPane>
        <div class="you can add any CSS classes here">
            2nd Pane
        </div>
    </SecondPane>
</SplitContainer>

**Comment by jsakamoto** [comment]
Hi @franky1017,

Thank you for providing the information. I got it. 

Unfortunately, the `FIrstPane` and `SecondPane` are not components; they are **parameters** of type `RenderFragment`, despite their appearances. Therefore, it is nonsense to apply parameters to render fragments.

Fortunately, you can specify an individual pane in CSS selectors. Please see also the sample code in the following link.

https://github.com/jsakamoto/Toolbelt.Blazor.SplitContainer/blob/main/SampleApps/BlazorWasmApp/App.razor.css#L20

I hope the sample code above Is helpful for you.

**Comment by franky1017** [comment]
Thank you for the clarification.

I have used the css selector to resolve my problem.

Love your component btw, keep it up!

Thanks,

Frank
