### ISSUE TITLE
Library requires FirstPaneSize

### ISSUE THREAD

**Issue by deeje2** [jsakamoto/Toolbelt.Blazor.SplitContainer#8]
**Version:** 1.1.2.1
**.NET Version:** 8.0
**Blazor Type:** Blazor Server

I'm having an issue where not setting `bind-FirstPaneSize="_PaneSize"` results in the splitter not working.
If I add the parameter, the splitter functions normally.
I'd ideally not like to set the size as I'd like a 50/50 split of the two panes.
Any suggestions?

**Comment by jsakamoto** [comment]
@deeje2 Thank you for asking.
Unfortunately, this library doesn't have the ability you want right now. However, I know that not only you but many people have wanted that ability. So, I'll try to implement a feature that will allow the component to work fine without explicit pane size specifications in the future.

**Comment by deeje2** [comment]
Thanks for the confirmation, @jsakamoto.  I appreciate you looking into implementing this in the future.

**Comment by jsakamoto** [comment]
Hi @deeje2,
Would you like to try the new version of the "Blazor SplitContainer" that was released today?

- https://www.nuget.org/packages/Toolbelt.Blazor.SplitContainer/#releasenotes-body-tab

It still requires either the `FirstPaneSzie` or `SecondPaneSize` parameter, but now, it supports "%" for the unit of the pane size. So, you can specify the initial `FirstPaneSize` value with 50.0%. That will split the container area as 50/50. I hope this solution fits your requirements.

**Comment by deeje2** [comment]
Hi @jsakamoto, apologise for the delay in getting back to you.

This fits my requirements perfectly! Thank you very much for implementing this.
